/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author alien
 */
import java.io.IOException;
import javax.swing.JOptionPane;
import weatherapp.WeatherService;
public class UIstart1 extends javax.swing.JFrame {
    String city;

    /**
     * Creates new form UIstart
     */
    public UIstart1() {
        initComponents();
    }
    
     public UIstart1(String c) {
        city=c;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        citynamehere = new javax.swing.JTextField();
        checkbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 80)); // NOI18N
        jLabel1.setText("Weather ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 50, 460, 68);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 55)); // NOI18N
        jLabel2.setText("ForeCast");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 140, 233, 59);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel3.setText("Enter City Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 250, 190, 32);

        citynamehere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citynamehereActionPerformed(evt);
            }
        });
        jPanel1.add(citynamehere);
        citynamehere.setBounds(200, 310, 390, 42);

        checkbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkbtn.setText("Check");
        checkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbtnActionPerformed(evt);
            }
        });
        jPanel1.add(checkbtn);
        checkbtn.setBounds(340, 380, 106, 42);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 20, 72, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 830, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void citynamehereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citynamehereActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_citynamehereActionPerformed

    private void checkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbtnActionPerformed
        // TODO add your handling code here:
       String cityName = citynamehere.getText().trim();
    if (!cityName.isEmpty()) {
        CityHolder.cityName = cityName; // Set the city name in CityHolder
        try {
            WeatherService weatherService = new WeatherService(CityHolder.latitude, CityHolder.longitude);
            double[] coordinates = weatherService.getCoordinates(cityName);

            // If coordinates are obtained, store them in CityHolder and move to next page
            if (coordinates != null && coordinates.length == 2) {
                CityHolder.latitude = coordinates[0];
                CityHolder.longitude = coordinates[1];
                options optionsFrame = new options();
                optionsFrame.setVisible(true);
                this.dispose(); // Close the current JFrame
            } else {
                // Display popup for incorrect city name
                JOptionPane.showMessageDialog(this, "Invalid city name!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            // Display popup for error in fetching coordinates
            JOptionPane.showMessageDialog(this, "Error fetching city coordinates!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Display popup for empty city name
        JOptionPane.showMessageDialog(this, "Please enter a city name!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_checkbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         UIstart UI= new UIstart();
        UI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIstart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIstart1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkbtn;
    private javax.swing.JTextField citynamehere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
