/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author alien
 */
import java.io.IOException;
//import java.text.SimpleDateFormat;
//import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import weatherapp.WeatherService;
public class Airpollution extends javax.swing.JFrame {
private final WeatherService weatherService;
    /**
     * Creates new form Air pollution
     * @throws java.io.IOException
     */
    public Airpollution() throws IOException {
        initComponents();
        weatherService = new WeatherService(CityHolder.latitude, CityHolder.longitude); // Initialize WeatherService
        initializeAirPollutionData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        City = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CO = new javax.swing.JLabel();
        NO = new javax.swing.JLabel();
        NOtwo = new javax.swing.JLabel();
        NHthree = new javax.swing.JLabel();
        SOtwo = new javax.swing.JLabel();
        PMlessthantwopointfive = new javax.swing.JLabel();
        PMlessthanten = new javax.swing.JLabel();
        Ozone = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        City.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jPanel1.add(City);
        City.setBounds(460, 20, 120, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Air Pollution In : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(168, 23, 289, 31);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Air Quality Index (AQI):");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 250, 36);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 80, 100, 57);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Carbon Monooxide (CO):");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(28, 147, 220, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nitric Oxide (NO):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(28, 193, 160, 29);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nitric Dioxide (NO₂)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(28, 248, 171, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("PM 2.5 (Partculate matter less than 2.5 microns ):");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(28, 309, 430, 31);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("PM 10 ( Partculate matter less than 10 microns):");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 370, 420, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Ammonia (NH₃) :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(443, 147, 150, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Sulphur Dioxide (SO₂) :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(443, 197, 210, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Ozone (O₃) :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(443, 254, 120, 25);

        CO.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(CO);
        CO.setBounds(250, 140, 110, 37);

        NO.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(NO);
        NO.setBounds(190, 190, 99, 37);

        NOtwo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(NOtwo);
        NOtwo.setBounds(210, 240, 99, 42);

        NHthree.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(NHthree);
        NHthree.setBounds(595, 147, 170, 40);

        SOtwo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(SOtwo);
        SOtwo.setBounds(641, 193, 140, 37);

        PMlessthantwopointfive.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(PMlessthantwopointfive);
        PMlessthantwopointfive.setBounds(460, 300, 280, 53);

        PMlessthanten.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(PMlessthanten);
        PMlessthanten.setBounds(451, 355, 300, 50);

        Ozone.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(Ozone);
        Ozone.setBounds(560, 250, 170, 42);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(0, 0, 0)));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(660, 400, 70, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aiirrr.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 800, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
    
    // Reopen the previous form (options form)
    options optionsForm = new options();
    optionsForm.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void initializeAirPollutionData() throws IOException {
        fetchAndDisplayAirPollutionData();
    }
    private void fetchAndDisplayAirPollutionData() {
    try {
        double latitude = CityHolder.latitude; // Example way of getting latitude
        double longitude = CityHolder.longitude; // Example way of getting longitude

        String pollutionDataJson = weatherService.fetchAirPollutionData(latitude, longitude);
        JSONObject pollutionData = new JSONObject(pollutionDataJson);
        updateUIWithAirPollutionData(pollutionData);
    } catch (JSONException | IOException ex) {
        JOptionPane.showMessageDialog(this, "Error fetching air pollution data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void updateUIWithAirPollutionData(JSONObject pollutionData) throws JSONException {
    
    City.setText(CityHolder.cityName); 
    JSONArray list = pollutionData.getJSONArray("list");
    if (list.length() > 0) {
        JSONObject mainPollution = list.getJSONObject(0).getJSONObject("main");
        int aqi = mainPollution.getInt("aqi");
        jLabel11.setText(String.valueOf(aqi)); // Set AQI
        JSONObject components = list.getJSONObject(0).getJSONObject("components");

        CO.setText(String.format("%.2f ppm", components.getDouble("co")));
        NO.setText(String.format("%.2f ppm", components.getDouble("no")));
        NOtwo.setText(String.format("%.2f ppm", components.getDouble("no2")));
        Ozone.setText(String.format("%.2f ppm", components.getDouble("o3")));
        SOtwo.setText(String.format("%.2f ppm", components.getDouble("so2")));
        PMlessthantwopointfive.setText(String.format("%.2f ppm", components.getDouble("pm2_5")));
        PMlessthanten.setText(String.format("%.2f ppm", components.getDouble("pm10")));
        NHthree.setText(String.format("%.2f ppm", components.getDouble("nh3")));
    } else {
        JOptionPane.showMessageDialog(this, "No air pollution data available.");
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Airpollution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Airpollution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Airpollution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Airpollution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Airpollution().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Airpollution.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel CO;
    private javax.swing.JLabel City;
    private javax.swing.JLabel NHthree;
    private javax.swing.JLabel NO;
    private javax.swing.JLabel NOtwo;
    private javax.swing.JLabel Ozone;
    private javax.swing.JLabel PMlessthanten;
    private javax.swing.JLabel PMlessthantwopointfive;
    private javax.swing.JLabel SOtwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
