/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author alien
 */
import java.io.IOException;
import java.text.DecimalFormat;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import weatherapp.WeatherService;

public class fivedaysforecast extends javax.swing.JFrame {

    /**
     * Creates new form five days forecast
     */
    public fivedaysforecast() {
        initComponents();
        try {
        WeatherService weatherService = new WeatherService(CityHolder.latitude, CityHolder.longitude);
        String forecastDataString = weatherService.fetchWeatherData(CityHolder.latitude, CityHolder.longitude);
        JSONObject forecastData = new JSONObject(forecastDataString); // Parse the string into JSONObject
        updateUI(forecastData);
    } catch (IOException | JSONException e) {
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Day1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Day2 = new javax.swing.JLabel();
        Day3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Day4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Day5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("5 Days Weather Forecast ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 30, 430, 37);

        Day1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Day1.setText("jLabel1");
        jPanel1.add(Day1);
        Day1.setBounds(110, 80, 640, 66);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Day 1:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 100, 60, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Day 2 : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 180, 70, 20);

        Day2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Day2.setText("jLabel5");
        jPanel1.add(Day2);
        Day2.setBounds(110, 150, 640, 67);

        Day3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Day3.setText("jLabel6");
        jPanel1.add(Day3);
        Day3.setBounds(120, 230, 650, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Day4:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 330, 60, 20);

        Day4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Day4.setText("jLabel8");
        jPanel1.add(Day4);
        Day4.setBounds(110, 300, 650, 68);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Day 5 :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 390, 80, 31);

        Day5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Day5.setText("jLabel10");
        jPanel1.add(Day5);
        Day5.setBounds(120, 370, 650, 60);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Day 3:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 250, 60, 20);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(670, 400, 90, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/partially cloudy.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();

        // Reopen the previous form (options form)
        options optionsForm = new options();
        optionsForm.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void updateUI(JSONObject forecastData) throws JSONException {
        JSONArray forecasts = forecastData.getJSONArray("list");
         DecimalFormat df = new DecimalFormat("#.#");
        for (int i = 0; i < forecasts.length(); i++) {
        JSONObject forecast = forecasts.getJSONObject(i);
        JSONObject main = forecast.getJSONObject("main");
        double temperatureKelvin = main.getDouble("temp");
        double temperatureCelsius = temperatureKelvin - 273.15; // Convert Kelvin to Celsius
        String formattedTemperature = df.format(temperatureCelsius); // Format temperature with one decimal place
        String description = forecast.getJSONArray("weather").getJSONObject(0).getString("description");

        // Convert timestamp to date or day of the week as needed
        // Update the corresponding JLabel based on the day
        switch (i) {
            case 0 -> Day1.setText("Temperature: " + formattedTemperature + "°C, Description: " + description);
            case 1 -> Day2.setText("Temperature: " + formattedTemperature + "°C, Description: " + description);
            case 2 -> Day3.setText("Temperature: " + formattedTemperature + "°C, Description: " + description);
            case 3 -> Day4.setText("Temperature: " + formattedTemperature + "°C, Description: " + description);
            case 4 -> Day5.setText("Temperature: " + formattedTemperature + "°C, Description: " + description);
            default -> {
            }
        }
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fivedaysforecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fivedaysforecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fivedaysforecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fivedaysforecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new fivedaysforecast().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Day1;
    private javax.swing.JLabel Day2;
    private javax.swing.JLabel Day3;
    private javax.swing.JLabel Day4;
    private javax.swing.JLabel Day5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
